title: Brian Treese
description: Angular tutorials, demos, and developer resources. Learn modern Angular techniques for components, signals, styling, animations, CDK, and more. Practical guides for Angular developers.

url: https://briantree.se
baseurl: /
paginate_path: "blog/page:num/"
permalink: /:title/

# Header Option
# header: large

sass:
  style: compressed
  sass_dir: _sass
  implementation: sass

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap, jekyll-feed]
paginate: 20

collections:
  filtered_posts:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      exclude_from_show: false

# Pagination Settings
pagination:
  enabled: true
  per_page: 20
  permalink: "/page/:num/"
  title: ":title - Page :num"
  limit: 0
  sort_field: "date"
  sort_reverse: true
  tag: ""
  exclude:
    tags: ["The DOM COM Show"]

navigation:
  - title: Home
    url: /index.html
  - title: Topics
    children:
      - title: "Angular Animations"
        url: /tags/angular-animations
      - title: "The Angular CDK"
        url: /tags/angular-cdk
      - title: "Styles in Angular"
        url: /tags/angular-styles
      - title: "The CDK Overlay"
        url: /tags/cdk-overlay
      - title: "Angular Components"
        url: /tags/angular-components
      - title: "Angular Signals"
        url: /tags/angular-signals
      - title: "CSS"
        url: /tags/css
      - title: "Accessibility"
        url: /tags/accessibility
  - title: About
    url: /about
  - title: YouTube
    url: https://www.youtube.com/@briantreese
  - title: Courses
    url: https://www.pluralsight.com/authors/brian-treese
  - title: Shop
    url: https://shop.briantree.se/

social:
  github: brianmtreese
  twitter: brianmtreese
  linkedin: brianmtreese
  youtube: briantreese

google_analytics: "G-JBQ6WT9CF9"

ads:
  - title: "Angular Shieldworks 'United by Craft' Heavyweight Tee"
    description: 'Built for the ones who code like it''s a trade. The Shieldworks "United by Craft" tee pays tribute to the builders who love the framework, the devs who stay true to their craft, their team, and their code. Printed on a premium Comfort Colors 1717, this shirt feels broken-in from day one but tough enough for everyday wear. Featuring the Shieldworks union-seal logo small on the chest and bold on the back, this shirt represents solidarity among Angular builders everywhere, forged in TypeScript, powered by pride.'
    url: "https://shop.briantree.se/products/shieldworks-local-201-united-by-craft-heavyweight-tee"
    images:
      - "https://imgproxy.fourthwall.com/HbKAZpuuspyeOHOLM25BdH1vPivL3EUbKefVBfY92YQ/w:1920/sm:1/enc/Cw_0griDNVk48BcU/CDXhclVDmeBVN4hk/JsKwNSL2xUb2N50X/UwqQfiHfu3FrWxC7/IUR2atB9zBohmCCJ/iwz9oXGM8R5GYxc4/p2L_RkOiNNgONSbV/TMJsxpmAkMeuaMqY/1QvgSWiZAwKwAsrY/lzGhOSbBHNxeJKmg/qf2fsWhJVSihzV0U/vrTaObfIINPfsiOZ/sn-StsM4VYobBgUZ/AAIBEQ"
      - "https://imgproxy.fourthwall.com/jk7S-gZx1q-mc0OY3026GB4HMg0SBAUhxIbMu81eHbw/w:1920/sm:1/enc/6r91-j3izujhZVyD/-BLXZEx3ElsMtiyN/kAka0106md_pC9sX/Ywoqojuw6GNKWD06/zkCmi-eSU4-k2Zt7/wjX6Aq2lI4ZvjuFe/Wk9wOuby_QwDyl31/Sit0xmyL3wFoGhAr/b802k_1sy_tJ4ba5/NF1v7WcplkC4JhRv/J8maop6OcOp62Vfi/KV1C-TVbm5fpVj3N/RgNtaFk-ilL94Wmw/t8ySzA"
  - title: "Angular Shieldworks 'United by Craft' Heavyweight Tee"
    description: 'Built for the ones who code like it''s a trade. The Shieldworks "United by Craft" tee pays tribute to the builders who love the framework, the devs who stay true to their craft, their team, and their code. Printed on a premium Comfort Colors 1717, this shirt feels broken-in from day one but tough enough for everyday wear. Featuring the Shieldworks union logo small on the chest and bold on the back, this shirt represents solidarity among Angular builders everywhere, forged in TypeScript, powered by pride.'
    url: "https://shop.briantree.se/products/shieldworks-local-201-united-by-craft-heavyweight-tee-2"
    images:
      - "https://imgproxy.fourthwall.com/UKtqibC8Lzh5sbEI3a1ClDUg-IaNs4ZLcY1vdckq26E/w:1920/sm:1/enc/7_E_m7rKLW7qn4vp/54PYtQQqjV_a15il/ndUvrgVBgshxAmeC/adCvqX1giyddqvB6/9C-y-uzZsoccxnLg/jDE5JvpJnwqueJZz/lLOkNjJMWId0F1Wb/GNuDoNsZsTzQpmef/DQg-_QGwYUtlBopF/S30YqHk5F564DbzO/7UAXVUVZMsDYXto_/t25oFqBvnoEU5HTK/h6HCAYHw0nryEREH/Rdwfbg"
      - "https://imgproxy.fourthwall.com/CvWWSLXOONZcMUTT-3NxBdwzpGi732uuZczY1YwC-Ek/w:1920/sm:1/enc/PJzJ_dQMsdiyIler/ABQIhyBefdWa2xX1/NqdJ7ZTrQcSbS16h/0rkyRV0-iPMI61zr/oO7djk3dKf0_UFpi/JOufCSIdputBatb8/lHgOg5slrhEUjZwJ/NQYZ3M0SIlhXSeB1/g1bpY_KAnQuvJreU/RcqMlhBDUVN695ia/WKnR77Eo4ZROIiAm/OtOY9vLqcbAL4cTm/Uj_0G42a5m1eEJM_/wvs7tQ"
  - title: "Angular Shieldworks 'United by Craft' Classic Hoodie"
    description: 'Built for late nights in the shop or long days in the codebase. The Shieldworks "United by Craft" hoodie is a heavyweight tribute to those who build things that last. Featuring the signature Shieldworks emblem  bold across the front, this piece stands for pride in your work, skill in your craft, and unity among builders. Printed on the Gildan Classic Hoodie, it delivers the perfect balance of comfort and grit. The double-lined hood and midweight fabric hold up to real wear on the job, at the desk, or out in the cold.'
    url: "https://shop.briantree.se/products/shieldworks-local-201-united-by-craft-classic-hoodie"
    images:
      - "https://imgproxy.fourthwall.com/smaEzdO4OQgc-NmhDTlP_QsK6oWnaTxF7DkKR_2e_HM/w:1920/sm:1/enc/7urVWar6OdrAkJ5N/YvCr_VvQshbiC0Rw/pSPWAC_6ohm39V1L/s9glKTL2vvW14Jcz/5n2fFwSqs589eQm5/IxHwLgMAm60s3BTU/2LFnTVG9Pek1V1_U/xR7079aigd8qStPi/7iJYNheporq6Ptqf/AR1RIs4ADYM5UyfN/7g3VC7SnyipJdU7O/kAOB-hr9_zmw_Qom/tAFby9RI-bbWneNJ/iCdw6A"
  - title: "Angular Shieldworks 'United by Craft' Classic Hoodie"
    description: 'Built for late nights in the shop or long days in the codebase. The Shieldworks "United by Craft" hoodie is a heavyweight tribute to those who build things that last. Featuring the signature Shieldworks emblem  bold across the front, this piece stands for pride in your work, skill in your craft, and unity among builders. Printed on the Gildan Classic Hoodie, it delivers the perfect balance of comfort and grit. The double-lined hood and midweight fabric hold up to real wear on the job, at the desk, or out in the cold.'
    url: "https://shop.briantree.se/products/copy-of-shieldworks-local-201-united-by-craft-classic-hoodie"
    images:
      - "https://imgproxy.fourthwall.com/uVbVfGaudXrJ217Cmq3Deb_q-77j-6oSeU3yYX5xIOE/w:1920/sm:1/enc/7afHwrdQyCTjigRu/ZjvYuR1F1JV-85iV/h1NC6dM13-cRpi9C/QMbS9Lxi1V8oXa3X/DQgo-5mxQYl1xJdi/sY6dvMVVvJKE16ZE/PiwpXHIMLUxqN04f/Z-T74D2-0DNekgm6/lM8sJKTBSv20d3pH/EHaqpyXkU58kEhGt/K4-DgBTiQazImgkm/NwSAjJwSPlhWC22g/6Zc2jDLSerVIL5T6/fdH2Tg"
# disqus:
#   shortname: briantreese
